- name: variables from files
  hosts: localhost 
  vars_files:
  - variables.yaml
  tasks:
  - name: prinitng variables
    ansible.builtin..debug:
      msg: "We are learinig {{NAME}}, DURATION:{{DURATION}}"
