-name: variables fro prompt
  hosts: localhost
  become: yes
  vars_prompt:
  - name: username
    prompt: plz enter your name:
    private: false
  - name: password
    prompt: plz enter your password
    private: true
  
  
  